AG-208: Fix marker interfaces for LocalXAResource/ConnectableLocalXAResource
agroal/agroal pull request #69
Opened 2023-05-28 16:08 UTC by graben

2023-07-20 16:11 UTC, barreiro commented
thanks @graben. I'm writing a couple more test cases and then I'll be able to merge this PR.

2023-08-02 11:01 UTC, barreiro requested changes

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/pom.xml
> +        </dependency>
We would like to avoid adding this dependency.

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/src/main/java/io/agroal/narayana/LocalXAResource.java
> +public class LocalXAResource implements XAResourceWrapper, LastResource, LastResourceCommitOptimisation {
We will not support LRCO for the reasons explained in https://jbossts.blogspot.com/2018/06/narayana-commit-markable-resource.html

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/src/main/java/io/agroal/narayana/NarayanaTransactionIntegration.java
> +        this.firstResource = firstResource;
throw `IllegalArgumentException` if both `fistResource` and `connectable`

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/src/main/java/io/agroal/narayana/NarayanaTransactionIntegration.java
> +                        }
in order to simplify the code a bit, this logic could be made a new method and then just use ` transactionManager.getTransaction().enlistResource( createXaResource( transactionAware, xaResource ) );`

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/src/main/java/io/agroal/narayana/FirstResourceBaseXAResource.java
> +public class FirstResourceBaseXAResource extends BaseXAResource implements FirstResource {
just curious, what are the use cases for `FirstResource` ??

2023-08-02 11:01 UTC, barreiro commented on agroal-narayana/src/main/java/io/agroal/narayana/ConnectableLocalXAResource.java
> +public class ConnectableLocalXAResource extends LocalXAResource implements ConnectableResource {
nothing wrong with this, but I want to point out that `ConnectableResource` must also be `LastResource`. then Narayana should be configured to use `LastResource` as the interface for last commit optimization, like in 
https://github.com/wildfly/wildfly/blob/29.0.0.Final/transactions/src/main/java/org/jboss/as/txn/service/JTAEnvironmentBeanService.java#L61 or like in the LRCO test that was recently added.

2023-08-02 18:21 UTC, graben commented on agroal-narayana/src/main/java/io/agroal/narayana/FirstResourceBaseXAResource.java
> +public class FirstResourceBaseXAResource extends BaseXAResource implements FirstResource {
Look at the linked issue from narayana-spring-boot [#85](https://github.com/snowdrop/narayana-spring-boot/issues/85). I think firstresource is the only way to solve this problem with Narayana.

2023-08-02 18:23 UTC, graben commented on agroal-narayana/pom.xml
> +        </dependency>
Done

2023-08-02 18:23 UTC, graben commented on agroal-narayana/src/main/java/io/agroal/narayana/NarayanaTransactionIntegration.java
> +        this.firstResource = firstResource;
Done

2023-08-02 18:23 UTC, graben commented on agroal-narayana/src/main/java/io/agroal/narayana/NarayanaTransactionIntegration.java
> +                        }
Done

2023-08-02 18:23 UTC, graben commented on agroal-narayana/src/main/java/io/agroal/narayana/ConnectableLocalXAResource.java
> +public class ConnectableLocalXAResource extends LocalXAResource implements ConnectableResource {
Done

2023-08-02 18:24 UTC, graben commented on agroal-narayana/src/main/java/io/agroal/narayana/LocalXAResource.java
> +public class LocalXAResource implements XAResourceWrapper, LastResource, LastResourceCommitOptimisation {
Revert done

2023-08-02 18:27 UTC, graben commented
@barreiro : Feedback added to PR

2023-08-04 11:17 UTC, barreiro approved these changes

2023-08-04 12:08 UTC, merged

2023-08-04 12:40 UTC, graben commented
Hi @barreiro, I'm just thinking about CommitMarkableResource wouldn't really work well with Spring-Boot as DataSource isn't being bind to JNDI. I think I will work on another improvement for this.

2023-08-04 14:29 UTC, barreiro commented
@graben that would be an improvement to either Narayana or Spring-Boot, no ?? 

The [`RecoveryModule`](https://github.com/jbosstm/narayana/blob/7.0.0.Final/ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore//7.0.0.Final/ArjunaJTA/jta/classes/com/arjuna/ats/internal/jta/recovery/arjunacore/CommitMarkableResourceRecordRecoveryModule.java#L210-L212CommitMarkableResourceRecordRecoveryModule.java#L210-L212) always fetch the datasource from JNDI.

By the way, I'm not sure Quarkus has everything need for CMR either.

2023-08-04 14:35 UTC, graben commented
@barreiro : It'll be an improvement to the Spring-Boot starter only. I'm just coding a bit in a WIP branch [AG-xxx](https://github.com/graben/agroal/tree/AG-xxx) I'll submit PR once ready.

2023-08-04 21:34 UTC, barreiro commented
@graben thanks for letting me know. I have left some comments.